# v=2
# print(v)
# print(type(v))
st="upflairs pvt ltd jaipur rajasthan upflairs"
print(st[17:23])
print(st.title())
print("title")
print(st.capitalize())
print("capitalize")
print(st.replace('upflairs','fip'))
print("replace")
print(st.find('p'))
print("title")
print(st.split())
print("title")
print(st.strip())
print("title")